services:

  todo-api:
    build:
      context: ./todo-api/php
      dockerfile: ./Dockerfile
      target: ${DOCKER_TARGET:-dev} # 環境変数で開発/本番を切り替え
    container_name: kzm-app-todo-api
    # volumes:
    # - ./todo-api/php/todo-app-api:/var/www/app/
    # - ./todo-api/php/script/startup.sh:/var/tmp/startup.sh
    ports:
      - 9000:9000
    working_dir: /var/www/app
    depends_on:
      - api-mysql
    env_file:
      - ./todo-api/php/todo-app-api/.env.docker
    networks:
      - kzm_app_network

  todo-nginx:
    build:
      context: ./todo-api/nginx
      dockerfile: ./Dockerfile
    container_name: kzm-app-todo-api-nginx
    ports:
      - 80:80
    working_dir: /var/www
    depends_on:
      - todo-api
    environment:
      FASTCGI_PASS: todo-api:9000
    networks:
      - kzm_app_network

  api-mysql:
    build:
      context: ./mysql/api
      dockerfile: ./Dockerfile
    container_name: kzm-app-api-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - kzm_todo_api_db_volume:/var/lib/mysql
      # - ./mysql/api/conf.d:/etc/mysql/conf.d
      # - ./mysql/api/init:/docker-entrypoint-initdb.d
    networks:
      - kzm_app_network

  keycloak-mysql:
    build:
      context: ./mysql/keycloak
      dockerfile: ./Dockerfile
    container_name: kzm-app-keycloak-db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - kzm_todo_api_keycloak_volume:/var/lib/mysql
      # - ./mysql/keycloak/conf.d:/etc/mysql/conf.d
      # - ./mysql/keycloak/init:/docker-entrypoint-initdb.d
    networks:
      - kzm_app_network

  keycloak:
    build:
      context: ./keycloak/
      dockerfile: Dockerfile
    container_name: kzm-app-keycloak
    ports:
      - 8080:8080
    command:
      - start-dev
    depends_on:
      - keycloak-mysql
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://localhost:8080/
      - KC_DB=mysql
      - KC_DB_URL_HOST=keycloak-mysql
      - KC_DB_URL_PORT=3306
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    networks:
      - kzm_app_network

volumes:
  kzm_todo_api_db_volume:
    name: kzm_todo_api_db_volume
  kzm_todo_api_keycloak_volume:
    name: kzm_todo_api_keycloak_volume

networks:
  kzm_app_network:
    name: kzm_app_network
