name: kzm
services:
  todo-app-api:
    build:
      context: ./todo-app/api
      dockerfile: ./Dockerfile
      target: ${DOCKER_TARGET:-dev} # 環境変数で開発/本番を切り替え
    container_name: kzm-app-todo-api
    # volumes:
    # - ./todo-app/api/todo-app-api:/var/www/app/
    # - ./todo-app/api/script/startup.sh:/var/tmp/startup.sh
    working_dir: /var/www/app
    depends_on:
      - api-mysql
    env_file:
      - ./todo-app/api/todo-app-api/.env.docker
    networks:
      - kzm_app_network

  todo-app-api-nginx:
    build:
      context: ./todo-app/nginx
      dockerfile: ./Dockerfile
    container_name: kzm-app-todo-api-nginx
    ports:
      - 80:80
    working_dir: /var/www
    depends_on:
      - todo-app-api
    environment:
      FASTCGI_PASS: todo-app-api:9000
    networks:
      - kzm_app_network

  api-mysql:
    build:
      context: ./mysql/api
      dockerfile: ./Dockerfile
    container_name: kzm-app-api-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - kzm_todo_api_db_volume:/var/lib/mysql
    networks:
      - kzm_app_network

  keycloak-mysql:
    build:
      context: ./mysql/keycloak
      dockerfile: ./Dockerfile
    container_name: kzm-app-keycloak-db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - kzm_todo_api_keycloak_volume:/var/lib/mysql
    networks:
      - kzm_app_network

  # Keycloakのプロキシサーバー
  # keycloak-nginx:
  #   build:
  #     context: ./keycloak/nginx
  #     dockerfile: Dockerfile
  #   container_name: kzm-app-keycloak-nginx
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - keycloak
  #   environment:
  #     - PROXY_PASS=http://keycloak:8080
  #   networks:
  #     - kzm_app_network

  keycloak:
    build:
      context: ./keycloak/
      dockerfile: Dockerfile
    container_name: kzm-app-keycloak
    ports:
      - 8080:8080
    # command:
    #   - start-dev
    command: [ "start-dev", "--import-realm", "--verbose" ]
    depends_on:
      - keycloak-mysql
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # - KC_HOSTNAME=http://localhost:8081 # KC_HOSTNAME_STRICTがあれば不要かも
      # - KC_HOSTNAME_STRICT=true
      # - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME=http://localhost:8080
      - KC_DB=mysql
      - KC_DB_URL_HOST=keycloak-mysql
      - KC_DB_URL_PORT=3306
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_HTTP_ENABLED=true
    networks:
      - kzm_app_network

volumes:
  kzm_todo_api_db_volume:
    name: kzm_todo_api_db_volume
  kzm_todo_api_keycloak_volume:
    name: kzm_todo_api_keycloak_volume

networks:
  kzm_app_network:
    name: kzm_app_network
